import type { Metadata } from "next";

import "./globals.css";
import { Menu } from "@/components/menu";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` min-h-screen h-auto w-full  antialiased`}
      >
        <Menu op1={"Home"} op2={"IMC"} op3={"Media"}></Menu>
        
        {children}

      </body>
    </html>
  );
}
